apiVersion: v1
kind: Secret
metadata:
  name: vault-config
  namespace: argocd
type: Opaque
stringData:
    AVP_TYPE: vault
    AVP_AUTH_TYPE: k8s
    AVP_K8S_ROLE: argocd
    VAULT_ADDR: http://vault.vault.svc.cluster.local:8200
